#!/bin/bash
set -e

# Command-line args: output paths
ASM_FILE="$1"
C_FILE="$2"

# Exceptions where the CPU pushes an error code (Intel manual, Vol 3, Table 6-1)
ISRS_WITH_ERROR_CODE="8 10 11 12 13 14 17 21 29 30"

# =========================================================
# Generate ASM file (256 ISR stubs using macros from isr.asm)
# =========================================================
echo "; Auto-generated by generate_isrs.sh - DO NOT EDIT" > "$ASM_FILE"
echo "" >> "$ASM_FILE"

for i in $(seq 0 255); do
    if echo "$ISRS_WITH_ERROR_CODE" | grep -qw "\b${i}\b"; then
        echo "ISR_ERRORCODE ${i}" >> "$ASM_FILE"
    else
        echo "ISR_NOERRORCODE ${i}" >> "$ASM_FILE"
    fi
done

# =========================================================
# Generate C file (extern declarations + InitializeGates)
# =========================================================
echo "// Auto-generated by generate_isrs.sh - DO NOT EDIT" > "$C_FILE"
echo "" >> "$C_FILE"
echo "#include \"idt.h\"" >> "$C_FILE"
echo "#include \"gdt.h\"" >> "$C_FILE"
echo "" >> "$C_FILE"

# Declare all 256 handlers as extern
for i in $(seq 0 255); do
    echo "extern void i686_ISR${i}();" >> "$C_FILE"
done

echo "" >> "$C_FILE"
echo "void i686_ISR_InitializeGates()" >> "$C_FILE"
echo "{" >> "$C_FILE"

for i in $(seq 0 255); do
    echo "    i686_IDT_SetGate(${i}, i686_ISR${i}, GDT_CODE_SEGMENT, IDT_FLAG_RING0 | IDT_FLAG_GATE_32BIT_INT);" >> "$C_FILE"
done

echo "}" >> "$C_FILE"
